language: rust
rust:
  - nightly
  - beta
  - stable
env:
  - GTK=3.4
  - GTK=3.18
addons:
  apt:
    packages:
    - libgtk-3-dev
script:
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b pending https://github.com/rust-gnome/examples _examples
  - cd _examples
  - ./build.sh
  - if [ "$GTK" = "3.18" ]; then FEAT="gtk_3_18"; fi
  - echo $FEAT
  - cargo build --features "$FEAT gtk/embed-lgpl-docs" --jobs 1
