[package]
name = "gtk-rs-lgpl-docs"
version = "0.0.1"
authors = [
    "GTK+ Project Developers",
    "Gtk-rs Project Developers",
]
license = "LGPL"

[lib]
name = "lgpl_docs"

[dependencies.rustdoc-stripper]
git = "https://github.com/GuillaumeGomez/rustdoc-stripper.git"
